# Generated by Django 4.1.4 on 2023-04-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeid', models.CharField(max_length=150)),
                ('timestamp_utc', models.TimeField()),
                ('status', models.CharField(max_length=150)),
            ],
        ),
    ]
