# Generated by Django 4.1.4 on 2023-04-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createmodels', '0002_alter_storestatus_timestamp_utc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storestatus',
            old_name='timestamp_utc',
            new_name='date_utc',
        ),
        migrations.AddField(
            model_name='storestatus',
            name='time_utc',
            field=models.TimeField(auto_now=True),
        ),
    ]
